# Generated by Django 5.0.3 on 2025-02-16 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0005_jobtiming'),
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeesProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('company_description', models.TextField(blank=True, null=True)),
                ('company_address', models.CharField(blank=True, max_length=255, null=True)),
                ('company_phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('company_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('corporate_office_address', models.CharField(blank=True, max_length=255, null=True)),
                ('gst_no', models.CharField(blank=True, max_length=20, null=True)),
                ('authorised_person_name', models.CharField(blank=True, max_length=255, null=True)),
                ('authorised_person_position', models.CharField(blank=True, max_length=100, null=True)),
                ('authorised_person_phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('authorised_person_email_address', models.EmailField(blank=True, max_length=254, null=True)),
                ('login_phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('login_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('login_password', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved')], default='requested', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employees_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_category', models.CharField(max_length=255)),
                ('job_sub_category', models.CharField(blank=True, max_length=255, null=True)),
                ('job_title', models.CharField(max_length=255)),
                ('job_description', models.TextField()),
                ('job_position', models.CharField(max_length=255)),
                ('require_qualification', models.CharField(max_length=255)),
                ('min_experience', models.IntegerField()),
                ('max_experience', models.IntegerField(blank=True, null=True)),
                ('min_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('require_skills', models.TextField(blank=True, null=True)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('last_interview_date', models.DateField(blank=True, null=True)),
                ('facilities', models.TextField(blank=True, null=True)),
                ('ctc_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('in_hand_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('salary_deduction_details', models.TextField(blank=True, null=True)),
                ('address_line_1', models.CharField(max_length=255)),
                ('address_line_2', models.CharField(blank=True, max_length=255, null=True)),
                ('area_landmark', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(default='India', max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('created_att', models.DateTimeField(auto_now_add=True)),
                ('statuss', models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved')], default='requested', max_length=10)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_posts', to=settings.AUTH_USER_MODEL)),
                ('job_timing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_dashboard.jobtiming')),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
