# Generated by Django 5.0.3 on 2025-02-12 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employeesprofile_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeesprofile',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('active', 'Active'), ('inactive', 'inactive')], default='requested', max_length=10),
        ),
    ]
