# Generated by Django 5.0.3 on 2025-02-17 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employeesprofile_jobpost_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='job_timing',
            field=models.CharField(max_length=255),
        ),
    ]
