# Generated by Django 5.0.3 on 2025-02-17 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0005_jobtiming'),
        ('employees', '0003_alter_jobpost_job_timing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='job_timing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_dashboard.jobtiming'),
        ),
    ]
