# Generated by Django 5.0.3 on 2025-02-13 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_employeesprofile_ccreated_at_employeesprofile_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeesprofile',
            old_name='ccreated_at',
            new_name='created_at',
        ),
    ]
