# Generated by Django 5.0.3 on 2025-02-13 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_rename_ccreated_at_employeesprofile_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeesprofile',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved')], default='requested', max_length=10),
        ),
    ]
