# Generated by Django 5.0.3 on 2025-02-14 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_alter_employeesprofile_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_category', models.CharField(max_length=255)),
                ('job_sub_category', models.CharField(blank=True, max_length=255, null=True)),
                ('job_title', models.CharField(max_length=255)),
                ('job_description', models.TextField()),
                ('job_position', models.CharField(max_length=255)),
                ('require_qualification', models.CharField(max_length=255)),
                ('min_experience', models.IntegerField()),
                ('max_experience', models.IntegerField(blank=True, null=True)),
                ('min_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('require_skills', models.TextField(blank=True, null=True)),
                ('job_timing', models.CharField(max_length=255)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('last_interview_date', models.DateField(blank=True, null=True)),
                ('facilities', models.TextField(blank=True, null=True)),
                ('ctc_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('in_hand_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('salary_deduction_details', models.TextField(blank=True, null=True)),
                ('address_line_1', models.CharField(max_length=255)),
                ('address_line_2', models.CharField(blank=True, max_length=255, null=True)),
                ('area_landmark', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(default='India', max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('created_att', models.DateTimeField(auto_now_add=True)),
                ('statuss', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
            ],
        ),
    ]
