# Generated by Django 5.0.3 on 2025-02-14 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_jobpost_posted_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='posted_by',
        ),
    ]
