# Generated by Django 5.0.3 on 2025-02-16 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0011_jobpost_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='statuss',
            field=models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved')], default='requested', max_length=10),
        ),
    ]
