# Generated by Django 5.0.3 on 2025-02-10 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdminStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email_address', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('client_code', models.CharField(blank=True, max_length=100, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('position', models.CharField(blank=True, max_length=100, null=True)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('pan_card_number', models.CharField(blank=True, max_length=20, null=True)),
                ('aadhar_number', models.CharField(blank=True, max_length=20, null=True)),
                ('pf_number', models.CharField(blank=True, max_length=20, null=True)),
                ('esic_number', models.CharField(blank=True, max_length=20, null=True)),
                ('nominee_name', models.CharField(blank=True, max_length=100, null=True)),
                ('nominee_phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('address_line_1', models.CharField(max_length=255)),
                ('address_line_2', models.CharField(blank=True, max_length=255, null=True)),
                ('location_area', models.CharField(blank=True, max_length=100, null=True)),
                ('pincode', models.CharField(blank=True, max_length=6, null=True)),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('account_name', models.CharField(blank=True, max_length=100, null=True)),
                ('account_number', models.CharField(blank=True, max_length=20, null=True)),
                ('ifsc_code', models.CharField(blank=True, max_length=20, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('branch_name', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('staff_role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_staffs', to='admin_dashboard.role')),
            ],
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_name', models.CharField(choices=[('Admin & Staffs', 'Admin & Staffs'), ('Admin & Staff Roles', 'Admin & Staff Roles'), ('Candidates', 'Candidates'), ('Employers', 'Employers'), ('Job Posts', 'Job Posts'), ('Interviews', 'Interviews'), ('HR - Education', 'HR - Education'), ('HR - Job Categories', 'HR - Job Categories'), ('HR - Job Timings', 'HR - Job Timings'), ('Pages - SEO Details', 'Pages - SEO Details'), ('Pages - Contact Info', 'Pages - Contact Info'), ('Pages - Terms & Policies', 'Pages - Terms & Policies'), ('Tools - Settings', 'Tools - Settings'), ('Tools - App Versions', 'Tools - App Versions')], max_length=255)),
                ('can_read', models.BooleanField(default=False)),
                ('can_write', models.BooleanField(default=False)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='admin_dashboard.role')),
            ],
        ),
    ]
