# Generated by Django 5.0.3 on 2025-02-16 08:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255)),
                ('job_description', models.TextField()),
                ('job_position', models.CharField(max_length=255)),
                ('require_qualification', models.CharField(max_length=255)),
                ('job_timing', models.CharField(max_length=255)),
                ('address_line1', models.CharField(max_length=255)),
                ('area_landmark', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('job_category', models.CharField(blank=True, max_length=255, null=True)),
                ('job_sub_category', models.CharField(blank=True, max_length=255, null=True)),
                ('min_experience', models.IntegerField(blank=True, null=True)),
                ('max_experience', models.IntegerField(blank=True, null=True)),
                ('min_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('require_skills', models.TextField(blank=True, null=True)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('last_interview_date', models.DateField(blank=True, null=True)),
                ('facilities', models.TextField(blank=True, null=True)),
                ('ctc_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('in_hand_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('salary_deduction_details', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_job_posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
