# Generated by Django 5.0.3 on 2025-02-16 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0002_jobpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='admin',
        ),
        migrations.AddField(
            model_name='jobpost',
            name='address_line2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='client_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
