# Generated by Django 5.0.3 on 2025-02-16 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0003_remove_jobpost_admin_jobpost_address_line2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobpost',
            old_name='address_line1',
            new_name='address_line_1',
        ),
        migrations.RenameField(
            model_name='jobpost',
            old_name='address_line2',
            new_name='address_line_2',
        ),
    ]
