# Generated by Django 5.0.3 on 2025-02-16 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0004_rename_address_line1_jobpost_address_line_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobTiming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('hours', models.IntegerField()),
                ('sort', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['sort'],
            },
        ),
    ]
