# Generated by Django 5.0.3 on 2025-02-02 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation', models.CharField(blank=True, max_length=200, null=True)),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('is_current_company', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True)),
                ('notice_period', models.PositiveIntegerField(blank=True, null=True)),
                ('started_working_from', models.DateField(blank=True, null=True)),
                ('key_skills', models.TextField(blank=True, null=True)),
                ('job_profile', models.TextField(blank=True, null=True)),
                ('responsible_person_name', models.CharField(blank=True, max_length=200, null=True)),
                ('responsible_person_mobile', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(blank=True, max_length=100, null=True)),
                ('company_name', models.CharField(blank=True, max_length=200, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_level', models.CharField(blank=True, choices=[('Any Graduate', 'Any Graduate'), ('12th Pass or Below 12th', '12th Pass or Below 12th'), ('ITI', 'ITI'), ('Diploma', 'Diploma'), ('Post Graduate', 'Post Graduate'), ('MBA', 'MBA')], max_length=50, null=True)),
                ('degree', models.CharField(blank=True, choices=[('B.Com', 'B.Com'), ('BBA', 'BBA'), ('BCA', 'BCA'), ('BA', 'BA'), ('BSC', 'BSC'), ('B.Pharma', 'B.Pharma'), ('B.Tech', 'B.Tech'), ('B.E', 'B.E'), ('Other', 'Other'), ('Electrical', 'Electrical'), ('Mechanical', 'Mechanical'), ('Chemistry', 'Chemistry'), ('COPA', 'COPA'), ('AOCP', 'AOCP'), ('CNC', 'CNC'), ('Fitter', 'Fitter'), ('Turner', 'Turner'), ('Machine Operator', 'Machine Operator'), ('Welder', 'Welder'), ('IT', 'IT'), ('Chemical', 'Chemical'), ('Fire & Safety', 'Fire & Safety'), ('Electronics', 'Electronics'), ('Civil', 'Civil'), ('Management', 'Management'), ('MA', 'MA'), ('M.COM', 'M.COM'), ('MBA', 'MBA'), ('M.C.A', 'M.C.A'), ('M.E', 'M.E'), ('M.TECH', 'M.TECH'), ('M.SC', 'M.SC'), ('M.PHARMA', 'M.PHARMA'), ('Human Resource', 'Human Resource')], max_length=100, null=True)),
                ('specialization', models.CharField(blank=True, max_length=100, null=True)),
                ('university', models.CharField(blank=True, max_length=200, null=True)),
                ('course_type', models.CharField(blank=True, choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time'), ('Correspondence / Distance Learning', 'Correspondence / Distance Learning')], max_length=50, null=True)),
                ('passing_year', models.PositiveIntegerField(blank=True, null=True)),
                ('education_board', models.CharField(blank=True, max_length=200, null=True)),
                ('school_medium', models.CharField(blank=True, max_length=100, null=True)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('phone2', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('whatsapp_number', models.CharField(blank=True, max_length=15, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Unknown', 'Unknown')], default='Unknown', max_length=10)),
                ('parent_name', models.CharField(blank=True, max_length=200, null=True)),
                ('parent_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('nominee_name', models.CharField(blank=True, max_length=200, null=True)),
                ('nominee_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('address_line1', models.CharField(blank=True, max_length=255, null=True)),
                ('address_line2', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('pincode', models.CharField(blank=True, max_length=10, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('highest_qualification', models.CharField(blank=True, max_length=200, null=True)),
                ('skills', models.TextField(blank=True, null=True)),
                ('work_status', models.CharField(blank=True, max_length=100, null=True)),
                ('total_experience_years', models.PositiveIntegerField(blank=True, null=True)),
                ('currently_working', models.BooleanField(default=False)),
                ('aadhar_number', models.CharField(blank=True, max_length=12, null=True)),
                ('pan_card_number', models.CharField(blank=True, max_length=10, null=True)),
                ('pf_number', models.CharField(blank=True, max_length=20, null=True)),
                ('esic_number', models.CharField(blank=True, max_length=20, null=True)),
                ('job_location', models.CharField(blank=True, max_length=200, null=True)),
                ('expected_salary_min', models.PositiveIntegerField(blank=True, null=True)),
                ('expected_salary_max', models.PositiveIntegerField(blank=True, null=True)),
                ('industries_required', models.BooleanField(default=False)),
                ('department_required', models.BooleanField(default=False)),
                ('shift_wise', models.BooleanField(default=False)),
                ('facilities_needed', models.BooleanField(default=False)),
                ('commitment_ready', models.BooleanField(default=False)),
            ],
        ),
    ]
