# Generated by Django 5.0.3 on 2025-02-02 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0002_experience_interview_myprofile_qualification_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Experience',
        ),
        migrations.DeleteModel(
            name='Interview',
        ),
        migrations.DeleteModel(
            name='MyProfile',
        ),
        migrations.DeleteModel(
            name='Qualification',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
