# Generated by Django 5.0.3 on 2025-02-02 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0003_delete_experience_delete_interview_delete_myprofile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_level', models.CharField(blank=True, choices=[('Any Graduate', 'Any Graduate'), ('12th Pass or Below 12th', '12th Pass or Below 12th'), ('ITI', 'ITI'), ('Diploma', 'Diploma'), ('Post Graduate', 'Post Graduate'), ('MBA', 'MBA')], max_length=50, null=True)),
                ('degree', models.CharField(blank=True, choices=[('B.Com', 'B.Com'), ('BBA', 'BBA'), ('BCA', 'BCA'), ('BA', 'BA'), ('BSC', 'BSC'), ('B.Pharma', 'B.Pharma'), ('B.Tech', 'B.Tech'), ('B.E', 'B.E'), ('Other', 'Other'), ('Electrical', 'Electrical'), ('Mechanical', 'Mechanical'), ('Chemistry', 'Chemistry'), ('COPA', 'COPA'), ('AOCP', 'AOCP'), ('CNC', 'CNC'), ('Fitter', 'Fitter'), ('Turner', 'Turner'), ('Machine Operator', 'Machine Operator'), ('Welder', 'Welder'), ('IT', 'IT'), ('Chemical', 'Chemical'), ('Fire & Safety', 'Fire & Safety'), ('Electronics', 'Electronics'), ('Civil', 'Civil'), ('Management', 'Management'), ('MA', 'MA'), ('M.COM', 'M.COM'), ('MBA', 'MBA'), ('M.C.A', 'M.C.A'), ('M.E', 'M.E'), ('M.TECH', 'M.TECH'), ('M.SC', 'M.SC'), ('M.PHARMA', 'M.PHARMA'), ('Human Resource', 'Human Resource')], max_length=100, null=True)),
                ('specialization', models.CharField(blank=True, max_length=100, null=True)),
                ('university', models.CharField(blank=True, max_length=200, null=True)),
                ('course_type', models.CharField(blank=True, choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time'), ('Correspondence / Distance Learning', 'Correspondence / Distance Learning')], max_length=50, null=True)),
                ('passing_year', models.PositiveIntegerField(blank=True, null=True)),
                ('education_board', models.CharField(blank=True, max_length=200, null=True)),
                ('school_medium', models.CharField(blank=True, max_length=100, null=True)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
        ),
    ]
