# Generated by Django 5.0.3 on 2025-02-02 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0004_qualification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation', models.CharField(blank=True, max_length=200, null=True)),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('is_current_company', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True)),
                ('notice_period', models.PositiveIntegerField(blank=True, null=True)),
                ('started_working_from', models.DateField(blank=True, null=True)),
                ('key_skills', models.TextField(blank=True, null=True)),
                ('job_profile', models.TextField(blank=True, null=True)),
                ('responsible_person_name', models.CharField(blank=True, max_length=200, null=True)),
                ('responsible_person_mobile', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
    ]
