# Generated by Django 5.0.3 on 2025-02-02 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0005_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('phone2', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('whatsapp_number', models.CharField(blank=True, max_length=15, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Unknown', 'Unknown')], default='Unknown', max_length=10)),
                ('parent_name', models.CharField(blank=True, max_length=200, null=True)),
                ('parent_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('nominee_name', models.CharField(blank=True, max_length=200, null=True)),
                ('nominee_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('address_line1', models.CharField(blank=True, max_length=255, null=True)),
                ('address_line2', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('pincode', models.CharField(blank=True, max_length=10, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('highest_qualification', models.CharField(blank=True, max_length=200, null=True)),
                ('skills', models.TextField(blank=True, null=True)),
                ('work_status', models.CharField(blank=True, max_length=100, null=True)),
                ('total_experience_years', models.PositiveIntegerField(blank=True, null=True)),
                ('currently_working', models.BooleanField(default=False)),
                ('aadhar_number', models.CharField(blank=True, max_length=12, null=True)),
                ('pan_card_number', models.CharField(blank=True, max_length=10, null=True)),
                ('pf_number', models.CharField(blank=True, max_length=20, null=True)),
                ('esic_number', models.CharField(blank=True, max_length=20, null=True)),
                ('job_location', models.CharField(blank=True, max_length=200, null=True)),
                ('expected_salary_min', models.PositiveIntegerField(blank=True, null=True)),
                ('expected_salary_max', models.PositiveIntegerField(blank=True, null=True)),
                ('industries_required', models.BooleanField(default=False)),
                ('department_required', models.BooleanField(default=False)),
                ('shift_wise', models.BooleanField(default=False)),
                ('facilities_needed', models.BooleanField(default=False)),
                ('commitment_ready', models.BooleanField(default=False)),
            ],
        ),
    ]
