# Generated by Django 5.0.3 on 2025-02-11 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0007_experience_user_qualification_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='work_status',
            field=models.CharField(choices=[('Fresher', 'Fresher'), ('Experience', 'Experience')], default='Fresher', max_length=10),
        ),
    ]
